[package]
name = "rustshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.6", features = ["headers"] }
axum-extra = { version = "0.3.4", features = ["spa"] }
clokwerk = "0.3.5"
dashmap = "5.3.4"
once_cell = "1.12.0"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sha2 = "0.10.2"
tokio = { version = "1.18.2", features = ["full"] }
tower-cookies = "0.6.0"
