[package]
name = "crabspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
axum = { version = "0.6.18", features = ["query"] }
axum-sessions = "0.5.0"
clokwerk = "0.4.0"
dashmap = "5.4.0"
once_cell = "1.17.1"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tera = "1.18.1"
tokio = { version = "1.28.1", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs"] }
uuid = { version = "1.3.2", features = ["v4", "serde"] }
