version: '3.2'

services:
  web:
    build: ./web
    restart: always
    ports:
      - "8443:443"
      - "8080:80"
    environment:
      - "BOT_HOST=bot"
      - "SAFE_ORIGINS=https://web,http://letters.asisctf.com,https://letters.asisctf.com,http://localhost:8080"
    volumes:
      - ./certs:/certs
  bot:
    build: ./bot
    restart: always
    ports:
      - "8000:8000"
    environment:
      - "FLAG=ASIS{test-flag}"
      - "CAPTCHA_SECRET="
    volumes:
      - ./certs:/certs